name: Deploy to Web

on:
  push:
    branches: [ main ]

jobs:
  web-deploy:
    name: Web Deploy
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: aakashthakare/flutter-gh-pages@main
        with:
          workingDir: ./