name: 'Deploy Flutter web app to github pages'
description: 'Automates the build and deployment of your Flutter web app on Github gh pages'
author: 'aakashthakare'

branding:
  color: blue
  icon: code

inputs:
  webRenderer:
    description: 'Which web renderer to be used, default is auto'
    required: false
    default: auto
  workingDir:
    description: 'The directory where the project is (default .)'
    required: false
    default: .
  targetBranch:
    required: false
    default: gh-pages
  baseHref:
    description: 'base href (if applicable)'
    required: false
    default: "/"
  customArgs:
    description: 'Custom args like: --dart-define="simple=example"'
    required: false
    default:

runs:
  using: 'composite'
  steps:
    - run: flutter build web --release --web-renderer=${{inputs.webRenderer}} --base-href ${{inputs.baseHref}} ${{inputs.customArgs}}
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git config user.name github-actions
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git config user.email github-actions@github.com
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git --work-tree build/web add --all
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git commit -m "Automatic deployment by github-actions"
      shell: bash
      working-directory: ${{inputs.workingDir}}
    - run: git push origin HEAD:${{inputs.targetBranch}} --force
      shell: bash
      working-directory: ${{inputs.workingDir}}